Script started on 2015年03月10日 (週二) 18時04分40秒
]0;F74036158@2015cpp: ~F74036158@2015cpp:~$ whoami;pwd
F74036158
/home/F74036158
]0;F74036158@2015cpp: ~F74036158@2015cpp:~$ git config -l
user.name=F74036158
user.email=F74036158@mail.ncku.edu.tw
]0;F74036158@2015cpp: ~F74036158@2015cpp:~$  git clone https://github.com/<your github account>/lab1.gi t[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cgit clone https://github.com/<your github account>/lab1.git [K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1P/lab1.git
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.gitF/lab1.git7/lab1.git4/lab1.git0/lab1.git3/lab1.git6/lab1.git1/lab1.git5/lab1.git8/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;F74036158@2015cpp: ~F74036158@2015cpp:~$ exit

Script done on 2015年03月10日 (週二) 18時05分45秒
